credentials:
  usernames:
    navya:
      email: navya@gmail.com
      name: Navya
      password: 'abc123'

cookie:
  expiry_days: 30
  key: some_signature_key
  name: roadmap_cookie

preauthorized:
  emails:
    - navya@gmail.com